//import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["400","500", "600", "700"],
  subsets: ["latin"]
});

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${poppins.className} bg-black text-white antialiased bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-gray-900 via-[#090821] to-black min-h-screen`}>
        {children}
      </body>
    </html>
  );
}
